package view;

import view.TelaCadastroFono;

public class TelaInicio extends javax.swing.JFrame {

    public TelaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_cadPct = new javax.swing.JButton();
        btn_cadFono = new javax.swing.JButton();
        btn_Audio = new javax.swing.JButton();
        btn_compararAudio = new javax.swing.JButton();
        lbl_logoInicio = new javax.swing.JLabel();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Audio - Início");
        setSize(new java.awt.Dimension(960, 540));

        jPanel1.setBackground(new java.awt.Color(214, 218, 219));

        btn_cadPct.setBackground(new java.awt.Color(4, 79, 87));
        btn_cadPct.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btn_cadPct.setForeground(new java.awt.Color(214, 218, 219));
        btn_cadPct.setText("Cadastro do paciente");
        btn_cadPct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadPctActionPerformed(evt);
            }
        });

        btn_cadFono.setBackground(new java.awt.Color(4, 79, 87));
        btn_cadFono.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btn_cadFono.setForeground(new java.awt.Color(214, 218, 219));
        btn_cadFono.setText("Cadastro do fonoaudiólogo");
        btn_cadFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadFonoActionPerformed(evt);
            }
        });

        btn_Audio.setBackground(new java.awt.Color(4, 79, 87));
        btn_Audio.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btn_Audio.setForeground(new java.awt.Color(214, 218, 219));
        btn_Audio.setText("AUDIOMETRIA");
        btn_Audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AudioActionPerformed(evt);
            }
        });

        btn_compararAudio.setBackground(new java.awt.Color(4, 79, 87));
        btn_compararAudio.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btn_compararAudio.setForeground(new java.awt.Color(214, 218, 219));
        btn_compararAudio.setText("Comparação");
        btn_compararAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compararAudioActionPerformed(evt);
            }
        });

        lbl_logoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EASY AUDIO LOGO.png"))); // NOI18N

        btn_sair.setBackground(new java.awt.Color(214, 218, 219));
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão sair.png"))); // NOI18N
        btn_sair.setOpaque(true);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cadPct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadFono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Audio, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(btn_compararAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_logoInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_logoInicio)
                    .addComponent(btn_sair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Audio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadPct, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_compararAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadFono, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadPctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadPctActionPerformed
        // TODO add your handling code here:
        TelaCadastroPaciente cadPct = new TelaCadastroPaciente();
        cadPct.setVisible(true);
        dispose();

    }//GEN-LAST:event_btn_cadPctActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_cadFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadFonoActionPerformed
        // TODO add your handling code here:

        TelaCadastroFono cadFono = new TelaCadastroFono();
        cadFono.setVisible(true);
        dispose();

    }//GEN-LAST:event_btn_cadFonoActionPerformed

    private void btn_AudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AudioActionPerformed
        // TODO add your handling code here:

        TelaAudiometria audio = new TelaAudiometria();
        audio.setVisible(true);
        dispose();

    }//GEN-LAST:event_btn_AudioActionPerformed

    private void btn_compararAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compararAudioActionPerformed
        // TODO add your handling code here:

        TelaComparacaoExames compExam = new TelaComparacaoExames();
        compExam.setVisible(true);
        dispose();


    }//GEN-LAST:event_btn_compararAudioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Audio;
    private javax.swing.JButton btn_cadFono;
    private javax.swing.JButton btn_cadPct;
    private javax.swing.JButton btn_compararAudio;
    private javax.swing.JButton btn_sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_logoInicio;
    // End of variables declaration//GEN-END:variables
}
