package view;

import data.FonoDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class TelaCadastroFono extends javax.swing.JFrame {

    private FonoDAO fonoDAO;

    public TelaCadastroFono() {
        initComponents();
        fonoDAO = new FonoDAO();
        // Conectar ao banco de dados usando FonoDAO
        if (fonoDAO.conectar()) {
            JOptionPane.showMessageDialog(this, "Conexão com o banco de dados estabelecida com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    //método para limpar os campos
    private void limparCampos() {
        jtf_nomeFono.setText("");
        jtf_crfaFono.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_logoCadFono = new javax.swing.JLabel();
        btn_voltarCadFono = new javax.swing.JButton();
        lbl_cadFono = new javax.swing.JLabel();
        lbl_nomeFono = new javax.swing.JLabel();
        jtf_nomeFono = new javax.swing.JTextField();
        lbl_crfa = new javax.swing.JLabel();
        jtf_crfaFono = new javax.swing.JTextField();
        btn_salvarFono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Easy Audio - Cadastro Fono");
        setBackground(new java.awt.Color(214, 218, 219));

        jPanel1.setBackground(new java.awt.Color(214, 218, 219));

        lbl_logoCadFono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EASY AUDIO LOGO.png"))); // NOI18N

        btn_voltarCadFono.setBackground(new java.awt.Color(214, 218, 219));
        btn_voltarCadFono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        btn_voltarCadFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarCadFonoActionPerformed(evt);
            }
        });

        lbl_cadFono.setBackground(new java.awt.Color(214, 218, 219));
        lbl_cadFono.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lbl_cadFono.setForeground(new java.awt.Color(4, 79, 87));
        lbl_cadFono.setText("CADASTRO DO FONOAUDIÓLOGO");

        lbl_nomeFono.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nomeFono.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lbl_nomeFono.setForeground(new java.awt.Color(6, 173, 153));
        lbl_nomeFono.setText("NOME:");

        jtf_nomeFono.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jtf_nomeFono.setForeground(new java.awt.Color(4, 79, 87));
        jtf_nomeFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomeFonoActionPerformed(evt);
            }
        });

        lbl_crfa.setBackground(new java.awt.Color(255, 255, 255));
        lbl_crfa.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lbl_crfa.setForeground(new java.awt.Color(6, 173, 153));
        lbl_crfa.setText("CRFa:");

        jtf_crfaFono.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jtf_crfaFono.setForeground(new java.awt.Color(4, 79, 87));
        jtf_crfaFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_crfaFonoActionPerformed(evt);
            }
        });

        btn_salvarFono.setBackground(new java.awt.Color(6, 173, 153));
        btn_salvarFono.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btn_salvarFono.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvarFono.setText("Salvar");
        btn_salvarFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarFonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lbl_cadFono)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_logoCadFono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_voltarCadFono)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_nomeFono, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_nomeFono, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_crfa, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_crfaFono, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btn_salvarFono, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_logoCadFono))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_voltarCadFono)))
                .addGap(8, 8, 8)
                .addComponent(lbl_cadFono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeFono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_nomeFono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_crfa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvarFono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_crfaFono, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarCadFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarCadFonoActionPerformed
        // TODO add your handling code here:
        TelaInicio ini = new TelaInicio();
        ini.setVisible(true);
        dispose();

    }//GEN-LAST:event_btn_voltarCadFonoActionPerformed

    private void jtf_nomeFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomeFonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomeFonoActionPerformed

    private void btn_salvarFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarFonoActionPerformed
        // Método para salvar os dados do paciente no banco de dados
        String nomeFono = jtf_nomeFono.getText();
        String crfa = jtf_crfaFono.getText();

        try {

            // Chama o método da classe FonoDAO para inserir os dados na tabela fonos
            if (fonoDAO.inserirFono(nomeFono, crfa)) {
                JOptionPane.showMessageDialog(this, "Fono cadastrado com sucesso!");
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o fono.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar os dados do fono: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

        //fechamento do salvar abaixo  
    }//GEN-LAST:event_btn_salvarFonoActionPerformed

    private void jtf_crfaFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_crfaFonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_crfaFonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvarFono;
    private javax.swing.JButton btn_voltarCadFono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtf_crfaFono;
    private javax.swing.JTextField jtf_nomeFono;
    private javax.swing.JLabel lbl_cadFono;
    private javax.swing.JLabel lbl_crfa;
    private javax.swing.JLabel lbl_logoCadFono;
    private javax.swing.JLabel lbl_nomeFono;
    // End of variables declaration//GEN-END:variables

}
