package view;

import data.AudiometriaDAO;
import javax.swing.JOptionPane;
import view.TelaInicio;

public class TelaComparacaoExames extends javax.swing.JFrame {

    private AudiometriaDAO audioDAO;

    public TelaComparacaoExames() {
        initComponents();
        audioDAO = new AudiometriaDAO();
        if (!audioDAO.conectar()) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Método para buscar e exibir os resultados da audiometria
    /*private void buscarResultadosAudiometria(String nomePaciente) {

        try {
            ResultSet resultados = audioDAO.buscarResultadosAudiometria(nomePaciente);

            if (resultados.next()) {
                jtf_dataAudio_CompID1.setText(resultados.getString("data_exame"));
                jtf_result05OD_CompID1.setText(resultados.getString("aud_VAD_05"));

                //     // Preencher os demais campos de resultados aqui...
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum resultado de audiometria encontrado para o paciente.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar resultados de audiometria: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_logoComp = new javax.swing.JLabel();
        btn_voltarComp = new javax.swing.JButton();
        lbl_compExames = new javax.swing.JLabel();
        lbl_nomePctComp = new javax.swing.JLabel();
        jtf_nomePctComp = new javax.swing.JTextField();
        btn_localizarComp = new javax.swing.JButton();
        lbl_CompAudioOD = new javax.swing.JLabel();
        lbl_CompAudioOE = new javax.swing.JLabel();
        lbl_CompAudioData = new javax.swing.JLabel();
        lbl_CompAudio05OD = new javax.swing.JLabel();
        lbl_CompAudio1OD = new javax.swing.JLabel();
        lbl_CompAudio2OD = new javax.swing.JLabel();
        lbl_CompAudio3OD = new javax.swing.JLabel();
        lbl_CompAudio4OD = new javax.swing.JLabel();
        lbl_CompAudio6OD = new javax.swing.JLabel();
        lbl_CompAudio8OD = new javax.swing.JLabel();
        lbl_CompAudio05OE = new javax.swing.JLabel();
        lbl_CompAudio1OE = new javax.swing.JLabel();
        lbl_CompAudio2OE = new javax.swing.JLabel();
        lbl_CompAudio3OE = new javax.swing.JLabel();
        lbl_CompAudio4OE = new javax.swing.JLabel();
        lbl_CompAudio6OE = new javax.swing.JLabel();
        lbl_CompAudio8OE = new javax.swing.JLabel();
        jtf_dataAudio_CompID1 = new javax.swing.JTextField();
        jtf_result05OD_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result1OD_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result2OD_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result3OD_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result4OD_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result6OD_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result8OD_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result05OE_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result1OE_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result2OE_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result3OE_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result4OE_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result6OE_CompID1 = new javax.swing.JFormattedTextField();
        jtf_result8OE_CompID1 = new javax.swing.JFormattedTextField();
        jtf_dataAudio_CompID2 = new javax.swing.JTextField();
        jtf_result05OD_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result1OD_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result2OD_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result3OD_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result4OD_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result6OD_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result8OD_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result05OE_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result1OE_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result2OE_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result3OE_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result4OE_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result6OE_CompID2 = new javax.swing.JFormattedTextField();
        jtf_result8OE_CompID2 = new javax.swing.JFormattedTextField();
        jtf_dataAudio_CompID3 = new javax.swing.JTextField();
        jtf_result05OD_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result1OD_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result2OD_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result3OD_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result4OD_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result6OD_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result8OD_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result05OE_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result1OE_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result2OE_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result3OE_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result4OE_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result6OE_CompID3 = new javax.swing.JFormattedTextField();
        jtf_result8OE_CompID3 = new javax.swing.JFormattedTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 218, 219));

        lbl_logoComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EASY AUDIO LOGO.png"))); // NOI18N

        btn_voltarComp.setBackground(new java.awt.Color(214, 218, 219));
        btn_voltarComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        btn_voltarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarCompActionPerformed(evt);
            }
        });

        lbl_compExames.setBackground(new java.awt.Color(214, 218, 219));
        lbl_compExames.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lbl_compExames.setForeground(new java.awt.Color(4, 79, 87));
        lbl_compExames.setText("COMPARAÇÃO DE EXAMES");

        lbl_nomePctComp.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nomePctComp.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lbl_nomePctComp.setForeground(new java.awt.Color(6, 173, 153));
        lbl_nomePctComp.setText("PACIENTE:");

        jtf_nomePctComp.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jtf_nomePctComp.setForeground(new java.awt.Color(4, 79, 87));
        jtf_nomePctComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomePctCompActionPerformed(evt);
            }
        });

        btn_localizarComp.setBackground(new java.awt.Color(6, 173, 153));
        btn_localizarComp.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btn_localizarComp.setForeground(new java.awt.Color(255, 255, 255));
        btn_localizarComp.setText("Localizar");
        btn_localizarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_localizarCompActionPerformed(evt);
            }
        });

        lbl_CompAudioOD.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        lbl_CompAudioOD.setForeground(new java.awt.Color(4, 79, 87));
        lbl_CompAudioOD.setText("Orelha direita");

        lbl_CompAudioOE.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        lbl_CompAudioOE.setForeground(new java.awt.Color(4, 79, 87));
        lbl_CompAudioOE.setText("Orelha esquerda");

        lbl_CompAudioData.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudioData.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudioData.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudioData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudioData.setText("DATA");
        lbl_CompAudioData.setOpaque(true);

        lbl_CompAudio05OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio05OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio05OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio05OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio05OD.setText("0,5KHz");
        lbl_CompAudio05OD.setOpaque(true);

        lbl_CompAudio1OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio1OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio1OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio1OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio1OD.setText("1KHz");
        lbl_CompAudio1OD.setOpaque(true);

        lbl_CompAudio2OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio2OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio2OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio2OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio2OD.setText("2KHz");
        lbl_CompAudio2OD.setOpaque(true);

        lbl_CompAudio3OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio3OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio3OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio3OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio3OD.setText("3KHz");
        lbl_CompAudio3OD.setOpaque(true);

        lbl_CompAudio4OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio4OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio4OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio4OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio4OD.setText("4KHz");
        lbl_CompAudio4OD.setOpaque(true);

        lbl_CompAudio6OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio6OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio6OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio6OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio6OD.setText("6KHz");
        lbl_CompAudio6OD.setOpaque(true);

        lbl_CompAudio8OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio8OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio8OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio8OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio8OD.setText("8KHz");
        lbl_CompAudio8OD.setOpaque(true);

        lbl_CompAudio05OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio05OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio05OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio05OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio05OE.setText("0,5KHz");
        lbl_CompAudio05OE.setOpaque(true);

        lbl_CompAudio1OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio1OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio1OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio1OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio1OE.setText("1KHz");
        lbl_CompAudio1OE.setOpaque(true);

        lbl_CompAudio2OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio2OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio2OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio2OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio2OE.setText("2KHz");
        lbl_CompAudio2OE.setOpaque(true);

        lbl_CompAudio3OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio3OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio3OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio3OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio3OE.setText("3KHz");
        lbl_CompAudio3OE.setOpaque(true);

        lbl_CompAudio4OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio4OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio4OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio4OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio4OE.setText("4KHz");
        lbl_CompAudio4OE.setOpaque(true);

        lbl_CompAudio6OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio6OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio6OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio6OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio6OE.setText("6KHz");
        lbl_CompAudio6OE.setOpaque(true);

        lbl_CompAudio8OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_CompAudio8OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_CompAudio8OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CompAudio8OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CompAudio8OE.setText("8KHz");
        lbl_CompAudio8OE.setOpaque(true);

        jtf_result05OD_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result05OD_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result05OD_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result1OD_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result1OD_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result1OD_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result2OD_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result2OD_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result2OD_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result3OD_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result3OD_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result3OD_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result4OD_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result4OD_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result4OD_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result6OD_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result6OD_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result6OD_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result8OD_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result8OD_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result8OD_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result05OE_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result05OE_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result05OE_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result1OE_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result1OE_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result1OE_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result2OE_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result2OE_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result2OE_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result3OE_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result3OE_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result3OE_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result4OE_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result4OE_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result4OE_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result6OE_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result6OE_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result6OE_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result8OE_CompID1.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result8OE_CompID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result8OE_CompID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result05OD_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result05OD_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result05OD_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result1OD_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result1OD_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result1OD_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result2OD_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result2OD_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result2OD_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result3OD_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result3OD_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result3OD_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result4OD_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result4OD_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result4OD_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result6OD_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result6OD_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result6OD_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result8OD_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result8OD_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result8OD_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result05OE_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result05OE_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result05OE_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result1OE_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result1OE_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result1OE_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result2OE_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result2OE_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result2OE_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result3OE_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result3OE_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result3OE_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result4OE_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result4OE_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result4OE_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result6OE_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result6OE_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result6OE_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result8OE_CompID2.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result8OE_CompID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result8OE_CompID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result05OD_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result05OD_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result05OD_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result1OD_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result1OD_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result1OD_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result2OD_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result2OD_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result2OD_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result3OD_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result3OD_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result3OD_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result4OD_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result4OD_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result4OD_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result6OD_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result6OD_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result6OD_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result8OD_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result8OD_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result8OD_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result05OE_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result05OE_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result05OE_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result1OE_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result1OE_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result1OE_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result2OE_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result2OE_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result2OE_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_result2OE_CompID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_result2OE_CompID3ActionPerformed(evt);
            }
        });

        jtf_result3OE_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result3OE_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result3OE_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result4OE_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result4OE_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result4OE_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_result4OE_CompID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_result4OE_CompID3ActionPerformed(evt);
            }
        });

        jtf_result6OE_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result6OE_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result6OE_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result8OE_CompID3.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result8OE_CompID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result8OE_CompID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_logoComp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_compExames)
                                .addGap(78, 78, 78)))
                        .addComponent(btn_voltarComp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_CompAudioData, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_dataAudio_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_dataAudio_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_CompAudioOD)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jtf_result05OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addComponent(jtf_result05OD_CompID1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addComponent(lbl_CompAudio05OD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(lbl_CompAudio1OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jtf_result1OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(lbl_CompAudio2OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jtf_result2OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(lbl_CompAudio3OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jtf_result3OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(lbl_CompAudio4OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jtf_result4OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(lbl_CompAudio6OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jtf_result6OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(lbl_CompAudio8OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jtf_result8OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jtf_result1OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jtf_result2OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jtf_result3OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jtf_result4OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jtf_result6OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jtf_result8OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtf_result05OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_result1OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_result2OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_result3OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_result4OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_result6OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_result8OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_CompAudioOE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jtf_result2OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lbl_CompAudio05OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jtf_result05OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lbl_CompAudio1OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jtf_result1OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jtf_result2OE_CompID1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                        .addComponent(lbl_CompAudio2OE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtf_result05OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtf_result05OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtf_result1OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jtf_result1OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jtf_result2OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jtf_result3OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtf_result4OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtf_result6OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lbl_CompAudio3OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jtf_result3OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lbl_CompAudio4OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jtf_result4OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lbl_CompAudio6OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jtf_result6OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jtf_result3OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtf_result4OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtf_result6OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtf_dataAudio_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(532, 532, 532)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_result8OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_CompAudio8OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtf_result8OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtf_result8OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nomePctComp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_nomePctComp))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(547, 547, 547)
                                .addComponent(btn_localizarComp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_voltarComp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_logoComp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_compExames)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nomePctComp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nomePctComp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_localizarComp)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_CompAudio8OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_result8OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_result8OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_CompAudioOE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl_CompAudio05OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_CompAudio1OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_CompAudio2OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_CompAudio3OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_CompAudio4OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_CompAudio6OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtf_result05OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result1OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result2OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result3OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result4OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result6OE_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtf_result05OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result1OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result2OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result3OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result4OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_result6OE_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lbl_CompAudioData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_dataAudio_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result05OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_CompAudioOD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CompAudio05OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CompAudio1OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CompAudio2OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CompAudio3OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CompAudio4OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CompAudio6OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CompAudio8OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_result05OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result1OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result2OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result3OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result4OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result6OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result8OD_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_dataAudio_CompID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_result05OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result1OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result2OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result3OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result4OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result6OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result8OD_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_dataAudio_CompID2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_result1OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result2OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result3OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result4OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result6OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result8OD_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result05OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result1OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result2OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result3OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result4OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result6OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_result8OE_CompID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarCompActionPerformed
        // TODO add your handling code here:

        TelaInicio ini = new TelaInicio();
        ini.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltarCompActionPerformed

    private void jtf_nomePctCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomePctCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomePctCompActionPerformed

    private void btn_localizarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_localizarCompActionPerformed
        // TODO add your handling code here:

        jtf_nomePctComp.getText();
    }//GEN-LAST:event_btn_localizarCompActionPerformed

    private void jtf_result2OE_CompID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_result2OE_CompID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_result2OE_CompID3ActionPerformed

    private void jtf_result4OE_CompID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_result4OE_CompID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_result4OE_CompID3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComparacaoExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComparacaoExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComparacaoExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComparacaoExames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComparacaoExames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_localizarComp;
    private javax.swing.JButton btn_voltarComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtf_dataAudio_CompID1;
    private javax.swing.JTextField jtf_dataAudio_CompID2;
    private javax.swing.JTextField jtf_dataAudio_CompID3;
    private javax.swing.JTextField jtf_nomePctComp;
    private javax.swing.JFormattedTextField jtf_result05OD_CompID1;
    private javax.swing.JFormattedTextField jtf_result05OD_CompID2;
    private javax.swing.JFormattedTextField jtf_result05OD_CompID3;
    private javax.swing.JFormattedTextField jtf_result05OE_CompID1;
    private javax.swing.JFormattedTextField jtf_result05OE_CompID2;
    private javax.swing.JFormattedTextField jtf_result05OE_CompID3;
    private javax.swing.JFormattedTextField jtf_result1OD_CompID1;
    private javax.swing.JFormattedTextField jtf_result1OD_CompID2;
    private javax.swing.JFormattedTextField jtf_result1OD_CompID3;
    private javax.swing.JFormattedTextField jtf_result1OE_CompID1;
    private javax.swing.JFormattedTextField jtf_result1OE_CompID2;
    private javax.swing.JFormattedTextField jtf_result1OE_CompID3;
    private javax.swing.JFormattedTextField jtf_result2OD_CompID1;
    private javax.swing.JFormattedTextField jtf_result2OD_CompID2;
    private javax.swing.JFormattedTextField jtf_result2OD_CompID3;
    private javax.swing.JFormattedTextField jtf_result2OE_CompID1;
    private javax.swing.JFormattedTextField jtf_result2OE_CompID2;
    private javax.swing.JFormattedTextField jtf_result2OE_CompID3;
    private javax.swing.JFormattedTextField jtf_result3OD_CompID1;
    private javax.swing.JFormattedTextField jtf_result3OD_CompID2;
    private javax.swing.JFormattedTextField jtf_result3OD_CompID3;
    private javax.swing.JFormattedTextField jtf_result3OE_CompID1;
    private javax.swing.JFormattedTextField jtf_result3OE_CompID2;
    private javax.swing.JFormattedTextField jtf_result3OE_CompID3;
    private javax.swing.JFormattedTextField jtf_result4OD_CompID1;
    private javax.swing.JFormattedTextField jtf_result4OD_CompID2;
    private javax.swing.JFormattedTextField jtf_result4OD_CompID3;
    private javax.swing.JFormattedTextField jtf_result4OE_CompID1;
    private javax.swing.JFormattedTextField jtf_result4OE_CompID2;
    private javax.swing.JFormattedTextField jtf_result4OE_CompID3;
    private javax.swing.JFormattedTextField jtf_result6OD_CompID1;
    private javax.swing.JFormattedTextField jtf_result6OD_CompID2;
    private javax.swing.JFormattedTextField jtf_result6OD_CompID3;
    private javax.swing.JFormattedTextField jtf_result6OE_CompID1;
    private javax.swing.JFormattedTextField jtf_result6OE_CompID2;
    private javax.swing.JFormattedTextField jtf_result6OE_CompID3;
    private javax.swing.JFormattedTextField jtf_result8OD_CompID1;
    private javax.swing.JFormattedTextField jtf_result8OD_CompID2;
    private javax.swing.JFormattedTextField jtf_result8OD_CompID3;
    private javax.swing.JFormattedTextField jtf_result8OE_CompID1;
    private javax.swing.JFormattedTextField jtf_result8OE_CompID2;
    private javax.swing.JFormattedTextField jtf_result8OE_CompID3;
    private javax.swing.JLabel lbl_CompAudio05OD;
    private javax.swing.JLabel lbl_CompAudio05OE;
    private javax.swing.JLabel lbl_CompAudio1OD;
    private javax.swing.JLabel lbl_CompAudio1OE;
    private javax.swing.JLabel lbl_CompAudio2OD;
    private javax.swing.JLabel lbl_CompAudio2OE;
    private javax.swing.JLabel lbl_CompAudio3OD;
    private javax.swing.JLabel lbl_CompAudio3OE;
    private javax.swing.JLabel lbl_CompAudio4OD;
    private javax.swing.JLabel lbl_CompAudio4OE;
    private javax.swing.JLabel lbl_CompAudio6OD;
    private javax.swing.JLabel lbl_CompAudio6OE;
    private javax.swing.JLabel lbl_CompAudio8OD;
    private javax.swing.JLabel lbl_CompAudio8OE;
    private javax.swing.JLabel lbl_CompAudioData;
    private javax.swing.JLabel lbl_CompAudioOD;
    private javax.swing.JLabel lbl_CompAudioOE;
    private javax.swing.JLabel lbl_compExames;
    private javax.swing.JLabel lbl_logoComp;
    private javax.swing.JLabel lbl_nomePctComp;
    // End of variables declaration//GEN-END:variables
}
