package view;

import data.AudiometriaDAO;
import data.PacienteDAO;
import data.FonoDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class TelaAudiometria extends javax.swing.JFrame {

    private PacienteDAO pacienteDAO;
    private FonoDAO fonoDAO;
    private AudiometriaDAO audioDAO;

    public TelaAudiometria() {
        initComponents();
        audioDAO = new AudiometriaDAO();
        pacienteDAO = new PacienteDAO();
        fonoDAO = new FonoDAO();
        //boolean conexoesEstabelecidas = false;

        if (!audioDAO.conectar() && !pacienteDAO.conectar() && !fonoDAO.conectar()) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
//conexoesEstabelecidas = true;
        }

        /*if (conexoesEstabelecidas) {
            JOptionPane.showMessageDialog(this, "Conexão com o banco de dados estabelecida com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
        }*/
        
        
    }

    //método para limpar os campos
    private void limparCampos() {
        jtf_nomePctAudio.setText("");
        jff_dataAudio.setText("");
        jtf_fonoAudio.setText("");
        jtf_result05OD.setText("");
        jtf_result1OD.setText("");
        jtf_result2OD.setText("");
        jtf_result3OD.setText("");
        jtf_result4OD.setText("");
        jtf_result6OD.setText("");
        jtf_result8OD.setText("");
        jtf_result05OE.setText("");
        jtf_result1OE.setText("");
        jtf_result2OE.setText("");
        jtf_result3OE.setText("");
        jtf_result4OE.setText("");
        jtf_result6OE.setText("");
        jtf_result8OE.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_result1OD3 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_logoAudio = new javax.swing.JLabel();
        btn_voltarAudio = new javax.swing.JButton();
        lbl_Audio = new javax.swing.JLabel();
        lbl_nomePctAudio = new javax.swing.JLabel();
        jtf_nomePctAudio = new javax.swing.JTextField();
        lbl_dataAudio = new javax.swing.JLabel();
        jff_dataAudio = new javax.swing.JFormattedTextField();
        btn_salvarAudio = new javax.swing.JButton();
        lbl_fonoAudio = new javax.swing.JLabel();
        jtf_fonoAudio = new javax.swing.JTextField();
        lbl_AudioOD = new javax.swing.JLabel();
        lbl_AudioOE = new javax.swing.JLabel();
        lbl_Audio05OD = new javax.swing.JLabel();
        lbl_Audio1OD = new javax.swing.JLabel();
        lbl_Audio2OD = new javax.swing.JLabel();
        lbl_Audio3OD = new javax.swing.JLabel();
        lbl_Audio4OD = new javax.swing.JLabel();
        lbl_Audio6OD = new javax.swing.JLabel();
        lbl_Audio8OD = new javax.swing.JLabel();
        lbl_Audio05OE = new javax.swing.JLabel();
        lbl_Audio1OE = new javax.swing.JLabel();
        lbl_Audio2OE = new javax.swing.JLabel();
        lbl_Audio3OE = new javax.swing.JLabel();
        lbl_Audio4OE = new javax.swing.JLabel();
        lbl_Audio6OE = new javax.swing.JLabel();
        lbl_Audio8OE = new javax.swing.JLabel();
        jtf_result05OD = new javax.swing.JFormattedTextField();
        jtf_result1OD = new javax.swing.JFormattedTextField();
        jtf_result2OD = new javax.swing.JFormattedTextField();
        jtf_result3OD = new javax.swing.JFormattedTextField();
        jtf_result4OD = new javax.swing.JFormattedTextField();
        jtf_result6OD = new javax.swing.JFormattedTextField();
        jtf_result8OD = new javax.swing.JFormattedTextField();
        jtf_result05OE = new javax.swing.JFormattedTextField();
        jtf_result1OE = new javax.swing.JFormattedTextField();
        jtf_result2OE = new javax.swing.JFormattedTextField();
        jtf_result3OE = new javax.swing.JFormattedTextField();
        jtf_result4OE = new javax.swing.JFormattedTextField();
        jtf_result6OE = new javax.swing.JFormattedTextField();
        jtf_result8OE = new javax.swing.JFormattedTextField();
        btn_buscarPct = new javax.swing.JButton();
        btn_buscarFono = new javax.swing.JButton();
        jtf_buscaNomes = new javax.swing.JTextField();

        jtf_result1OD3.setForeground(new java.awt.Color(117, 160, 173));
        jtf_result1OD3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result1OD3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Easy Audio - Audiometria");
        setBackground(new java.awt.Color(214, 218, 219));

        jPanel1.setBackground(new java.awt.Color(214, 218, 219));

        lbl_logoAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EASY AUDIO LOGO.png"))); // NOI18N

        btn_voltarAudio.setBackground(new java.awt.Color(214, 218, 219));
        btn_voltarAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        btn_voltarAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarAudioActionPerformed(evt);
            }
        });

        lbl_Audio.setBackground(new java.awt.Color(214, 218, 219));
        lbl_Audio.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lbl_Audio.setForeground(new java.awt.Color(4, 79, 87));
        lbl_Audio.setText("AUDIOMETRIA");

        lbl_nomePctAudio.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nomePctAudio.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lbl_nomePctAudio.setForeground(new java.awt.Color(6, 173, 153));
        lbl_nomePctAudio.setText("PACIENTE:");

        jtf_nomePctAudio.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jtf_nomePctAudio.setForeground(new java.awt.Color(4, 79, 87));
        jtf_nomePctAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomePctAudioActionPerformed(evt);
            }
        });

        lbl_dataAudio.setBackground(new java.awt.Color(255, 255, 255));
        lbl_dataAudio.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lbl_dataAudio.setForeground(new java.awt.Color(6, 173, 153));
        lbl_dataAudio.setText("DATA:");

        jff_dataAudio.setForeground(new java.awt.Color(4, 79, 87));
        try {
            jff_dataAudio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jff_dataAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jff_dataAudioActionPerformed(evt);
            }
        });

        btn_salvarAudio.setBackground(new java.awt.Color(6, 173, 153));
        btn_salvarAudio.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btn_salvarAudio.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvarAudio.setText("Salvar");
        btn_salvarAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarAudioActionPerformed(evt);
            }
        });

        lbl_fonoAudio.setBackground(new java.awt.Color(255, 255, 255));
        lbl_fonoAudio.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lbl_fonoAudio.setForeground(new java.awt.Color(6, 173, 153));
        lbl_fonoAudio.setText("FONO:");

        jtf_fonoAudio.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jtf_fonoAudio.setForeground(new java.awt.Color(4, 79, 87));

        lbl_AudioOD.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        lbl_AudioOD.setForeground(new java.awt.Color(4, 79, 87));
        lbl_AudioOD.setText("Orelha direita");

        lbl_AudioOE.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        lbl_AudioOE.setForeground(new java.awt.Color(4, 79, 87));
        lbl_AudioOE.setText("Orelha esquerda");

        lbl_Audio05OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio05OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio05OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio05OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio05OD.setText("0,5KHz");
        lbl_Audio05OD.setOpaque(true);

        lbl_Audio1OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio1OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio1OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio1OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio1OD.setText("1KHz");
        lbl_Audio1OD.setOpaque(true);

        lbl_Audio2OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio2OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio2OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio2OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio2OD.setText("2KHz");
        lbl_Audio2OD.setOpaque(true);

        lbl_Audio3OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio3OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio3OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio3OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio3OD.setText("3KHz");
        lbl_Audio3OD.setOpaque(true);

        lbl_Audio4OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio4OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio4OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio4OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio4OD.setText("4KHz");
        lbl_Audio4OD.setOpaque(true);

        lbl_Audio6OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio6OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio6OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio6OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio6OD.setText("6KHz");
        lbl_Audio6OD.setOpaque(true);

        lbl_Audio8OD.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio8OD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio8OD.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio8OD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio8OD.setText("8KHz");
        lbl_Audio8OD.setOpaque(true);

        lbl_Audio05OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio05OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio05OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio05OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio05OE.setText("0,5KHz");
        lbl_Audio05OE.setOpaque(true);

        lbl_Audio1OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio1OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio1OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio1OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio1OE.setText("1KHz");
        lbl_Audio1OE.setOpaque(true);

        lbl_Audio2OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio2OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio2OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio2OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio2OE.setText("2KHz");
        lbl_Audio2OE.setOpaque(true);

        lbl_Audio3OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio3OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio3OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio3OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio3OE.setText("3KHz");
        lbl_Audio3OE.setOpaque(true);

        lbl_Audio4OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio4OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio4OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio4OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio4OE.setText("4KHz");
        lbl_Audio4OE.setOpaque(true);

        lbl_Audio6OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio6OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio6OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio6OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio6OE.setText("6KHz");
        lbl_Audio6OE.setOpaque(true);

        lbl_Audio8OE.setBackground(new java.awt.Color(117, 160, 173));
        lbl_Audio8OE.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        lbl_Audio8OE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Audio8OE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Audio8OE.setText("8KHz");
        lbl_Audio8OE.setOpaque(true);

        jtf_result05OD.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result05OD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result05OD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result1OD.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result1OD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result1OD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result2OD.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result2OD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result2OD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result3OD.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result3OD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result3OD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result4OD.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result4OD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result4OD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result6OD.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result6OD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result6OD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result8OD.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result8OD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result8OD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result05OE.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result05OE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result05OE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result1OE.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result1OE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result1OE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result2OE.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result2OE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result2OE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result3OE.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result3OE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result3OE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result4OE.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result4OE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result4OE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result6OE.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result6OE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result6OE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_result8OE.setForeground(new java.awt.Color(4, 79, 87));
        jtf_result8OE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtf_result8OE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_buscarPct.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_buscarPct.setForeground(new java.awt.Color(4, 79, 87));
        btn_buscarPct.setText("Buscar nome");
        btn_buscarPct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarPctActionPerformed(evt);
            }
        });

        btn_buscarFono.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_buscarFono.setForeground(new java.awt.Color(4, 79, 87));
        btn_buscarFono.setText("Buscar fono");
        btn_buscarFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarFonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_logoAudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltarAudio)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salvarAudio)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lbl_AudioOD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_result05OD, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(lbl_Audio05OD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio1OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result1OD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio2OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result2OD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio3OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result3OD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio4OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result4OD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio6OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result6OD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio8OD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result8OD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio05OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result05OE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio1OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result1OE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_AudioOE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_result2OE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(lbl_Audio2OE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio3OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result3OE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio4OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result4OE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio6OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result6OE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_Audio8OE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_result8OE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lbl_dataAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_nomePctAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jff_dataAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_fonoAudio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_fonoAudio))
                            .addComponent(jtf_nomePctAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Audio)
                                .addGap(202, 202, 202))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_buscaNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_buscarPct)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_buscarFono)))
                                .addGap(38, 38, 38)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_voltarAudio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_logoAudio)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Audio)))
                .addGap(18, 18, 18)
                .addComponent(jtf_buscaNomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscarFono)
                    .addComponent(btn_buscarPct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomePctAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_nomePctAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jff_dataAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dataAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fonoAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_fonoAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_AudioOD)
                    .addComponent(lbl_AudioOE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Audio05OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio1OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio2OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio3OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio4OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio6OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio8OD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio05OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio1OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio2OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio3OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio4OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio6OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Audio8OE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_result05OD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result1OD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result2OD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result3OD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result4OD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result6OD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result8OD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result05OE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result1OE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result2OE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result3OE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result4OE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result6OE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_result8OE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_salvarAudio)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarAudioActionPerformed
        // TODO add your handling code here:

        TelaInicio ini = new TelaInicio();
        ini.setVisible(true);
        dispose();

    }//GEN-LAST:event_btn_voltarAudioActionPerformed

    private void jtf_nomePctAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomePctAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomePctAudioActionPerformed

    private void jff_dataAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jff_dataAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jff_dataAudioActionPerformed

    private void btn_salvarAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarAudioActionPerformed
        // TODO add your handling code here:

        // Recupera as infos inseridas pelo usuário
        String pacienteNome = jtf_nomePctAudio.getText();
        String dataExameStr = jff_dataAudio.getText();
        String fonoNome = jtf_fonoAudio.getText();
        int resultVA05OD = Integer.parseInt(jtf_result05OD.getText());
        int resultVA1OD = Integer.parseInt(jtf_result1OD.getText());
        int resultVA2OD = Integer.parseInt(jtf_result2OD.getText());
        int resultVA3OD = Integer.parseInt(jtf_result3OD.getText());
        int resultVA4OD = Integer.parseInt(jtf_result4OD.getText());
        int resultVA6OD = Integer.parseInt(jtf_result6OD.getText());
        int resultVA8OD = Integer.parseInt(jtf_result8OD.getText());
        int resultVA05OE = Integer.parseInt(jtf_result05OE.getText());
        int resultVA1OE = Integer.parseInt(jtf_result1OE.getText());
        int resultVA2OE = Integer.parseInt(jtf_result2OE.getText());
        int resultVA3OE = Integer.parseInt(jtf_result3OE.getText());
        int resultVA4OE = Integer.parseInt(jtf_result4OE.getText());
        int resultVA6OE = Integer.parseInt(jtf_result6OE.getText());
        int resultVA8OE = Integer.parseInt(jtf_result8OE.getText());

        try {
            // Buscar IDs do paciente e do fono
            int pacienteId = pacienteDAO.buscarIdPaciente(pacienteNome);
            int fonoId = fonoDAO.buscarIdFono(fonoNome);

            // Convertendo a data para o formato do BD
            SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatoBD = new SimpleDateFormat("yyyy-MM-dd");
            Date dataExame = formatoEntrada.parse(dataExameStr);
            String dataExameFormatada = formatoBD.format(dataExame);

            // Chamando o método de inserção da audiometria
            if (audioDAO.inserirAudiometria(pacienteId, dataExameFormatada, fonoId, resultVA05OD, resultVA1OD, resultVA2OD, resultVA3OD, resultVA4OD, resultVA6OD, resultVA8OD, resultVA05OE, resultVA1OE, resultVA2OE, resultVA3OE, resultVA4OE, resultVA6OE, resultVA8OE)) {
                JOptionPane.showMessageDialog(this, "Audiometria salva com sucesso!");
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar audiometria.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar audiometria: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            Logger.getLogger(TelaAudiometria.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_salvarAudioActionPerformed

    private void btn_buscarPctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarPctActionPerformed
        // TODO add your handling code here:
        String nomePaciente = jtf_buscaNomes.getText();
        String nomePacienteEncontrado = null;

        try {
            // Ver se DAO esta inicializado
            if (pacienteDAO != null) {
                nomePacienteEncontrado = pacienteDAO.buscarNomePaciente(nomePaciente);

                // Se o nome do paciente foi encontrado
                if (nomePacienteEncontrado != null) {
                    jtf_nomePctAudio.setText(nomePacienteEncontrado);
                } else {
                    JOptionPane.showMessageDialog(this, "Paciente não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro: pacienteDAO não inicializado.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAudiometria.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao buscar paciente: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_buscarPctActionPerformed

    private void btn_buscarFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarFonoActionPerformed
        // TODO add your handling code here:
        String nomeFono = jtf_buscaNomes.getText();
        String nomeFonoEncontrado = null;

        try {
            // Ver se DAO esta inicializado
            if (fonoDAO != null) {
                nomeFonoEncontrado = fonoDAO.buscarNomeFono(nomeFono);

                // Verifica se fono encontrada
                if (nomeFonoEncontrado != null) {
                    jtf_fonoAudio.setText(nomeFonoEncontrado);
                } else {
                    JOptionPane.showMessageDialog(this, "Fonoaudiólogo não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro: fonoDAO não inicializado.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAudiometria.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao buscar fonoaudiólogo: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_buscarFonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAudiometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAudiometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAudiometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAudiometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAudiometria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarFono;
    private javax.swing.JButton btn_buscarPct;
    private javax.swing.JButton btn_salvarAudio;
    private javax.swing.JButton btn_voltarAudio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jff_dataAudio;
    private javax.swing.JTextField jtf_buscaNomes;
    private javax.swing.JTextField jtf_fonoAudio;
    private javax.swing.JTextField jtf_nomePctAudio;
    private javax.swing.JFormattedTextField jtf_result05OD;
    private javax.swing.JFormattedTextField jtf_result05OE;
    private javax.swing.JFormattedTextField jtf_result1OD;
    private javax.swing.JFormattedTextField jtf_result1OD3;
    private javax.swing.JFormattedTextField jtf_result1OE;
    private javax.swing.JFormattedTextField jtf_result2OD;
    private javax.swing.JFormattedTextField jtf_result2OE;
    private javax.swing.JFormattedTextField jtf_result3OD;
    private javax.swing.JFormattedTextField jtf_result3OE;
    private javax.swing.JFormattedTextField jtf_result4OD;
    private javax.swing.JFormattedTextField jtf_result4OE;
    private javax.swing.JFormattedTextField jtf_result6OD;
    private javax.swing.JFormattedTextField jtf_result6OE;
    private javax.swing.JFormattedTextField jtf_result8OD;
    private javax.swing.JFormattedTextField jtf_result8OE;
    private javax.swing.JLabel lbl_Audio;
    private javax.swing.JLabel lbl_Audio05OD;
    private javax.swing.JLabel lbl_Audio05OE;
    private javax.swing.JLabel lbl_Audio1OD;
    private javax.swing.JLabel lbl_Audio1OE;
    private javax.swing.JLabel lbl_Audio2OD;
    private javax.swing.JLabel lbl_Audio2OE;
    private javax.swing.JLabel lbl_Audio3OD;
    private javax.swing.JLabel lbl_Audio3OE;
    private javax.swing.JLabel lbl_Audio4OD;
    private javax.swing.JLabel lbl_Audio4OE;
    private javax.swing.JLabel lbl_Audio6OD;
    private javax.swing.JLabel lbl_Audio6OE;
    private javax.swing.JLabel lbl_Audio8OD;
    private javax.swing.JLabel lbl_Audio8OE;
    private javax.swing.JLabel lbl_AudioOD;
    private javax.swing.JLabel lbl_AudioOE;
    private javax.swing.JLabel lbl_dataAudio;
    private javax.swing.JLabel lbl_fonoAudio;
    private javax.swing.JLabel lbl_logoAudio;
    private javax.swing.JLabel lbl_nomePctAudio;
    // End of variables declaration//GEN-END:variables
}
